### ISSUE TITLE
Removing ac-html dependency

### ISSUE THREAD

**Issue by CestDiego** [osv/company-web#1]
I see you created https://github.com/osv/web-completion-data .

So is this a step forward to removing ac-html as a hard dependency for company-mode users? :)

**Comment by osv** [comment]
Hello,

That is why was created this package, its done already. Run again `list-packages` :)

**Comment by CestDiego** [comment]
omg :3 thank you! :) I'm working on putting it into spacemacs. I love the docummentation popup.
[![alt](http://imgur.com/w3P9eN9.png)](http://imgur.com/w3P9eN9)

Is there a way to have angularjs cmpletion too though? like ng-directives... What would one need to do to make this work? :D I'm really interested in doing some kind of completion like this for angular, with the doc and stuff.

**Comment by osv** [comment]
I have plan for adding angular framework, but I found https://github.com/magnars/angular-snippets.el and drop. I think it much usefull, and you may use company-yasnippet!

**Comment by CestDiego** [comment]
Thank you again. :)

**Comment by osv** [comment]
But if you decide make ng-XXX with doc, I may recommend you https://github.com/osv/h5doc That script I use for generate bootstrap completion data https://github.com/osv/ac-html-bootstrap/blob/master/bootstrap.yaml.

**Comment by CestDiego** [comment]
ok. will keep this in mind
