### ISSUE TITLE
Cannot replicate ac-html screencast

### ISSUE THREAD

**Issue by louy2** [osv/company-web#4]
The screencase from ac-html: https://www.youtube.com/watch?v=UrXNgrN4d5Y

With `company-web-html` in the current `company-backends`, typing `<` doesn't trigger anything.

**Comment by osv** [comment]
Try `company-diag` when you typed `<`, it must show something like

```
Used backend: company-web-html
Prefix: ""
Completions:
  #("a" 0 1 (annotation "html")) "html"
  #("abbr" 0 4 (annotation "html")) "html"
  #("acronym" 0 7 (annotation "html")) "html"
...
```

If so, then you should configure `company-minimum-prefix-length` (default is 3), set it to `0` and popup start after you type any char

**Comment by louy2** [comment]
Thx!
