### ISSUE TITLE
Memory leak with company-web-html

### ISSUE THREAD

**Issue by axyz** [osv/company-web#7]
Noticed using web-mode. 

Please see https://github.com/syl20bnr/spacemacs/issues/3263 for more details. 

After some regular usage it fill the whole ram and emacs crashes making impossible to use it for regular work. 

Please Check if you are able to replicate.

**Comment by osv** [comment]
Thanks for report!

Can you tell me:
1. how many your pc have memory
2. Maybe you see same behavior on plain `html-mode` or `jade-mode` that may use `company-web`?

Must to say I never work with web-mode for very long session to keep find that problem. 

PS, Nice util for humanize memory usage  https://raw.githubusercontent.com/emacsmirror/memory-usage/master/memory-usage.el

**Comment by axyz** [comment]
my pc has 8gb of ram, this evening I'm going to do some tests in html mode

**Comment by osv** [comment]
maybe try `memory-usage.el` to diag, maybe it give some interesting facts, but need catch stats before it crash :)

**Comment by osv** [comment]
will be fixed in next version. It was bad idea to load file via `find-file-noselect` because it run all hooks which increase mem+cpu usage and

**Comment by osv** [comment]
I think it is fixed in scope of https://github.com/osv/company-web/pull/15
