### ISSUE TITLE
Error when trying to auto-complete in "style" attribute with company-web-complete-css

### ISSUE THREAD

**Issue by aiguofer** [osv/company-web#8]
When I try to complete in `<div style="|"` I get the following in `*Messages*`:

```
Company: An error occurred in auto-begin
Company: backend company-web-html error "Symbol's function definition is void: ac-css-prefix" with args (candidates ma)
company-begin-backend: Cannot complete at point
```

**Comment by osv** [comment]
Confirmed, when I create this package, I use ac-html as start point, and many code was migrated from `ac-html` and `ac-css-prefix` too, which is part of auto-complete. Will be fixed in next few days when I get more time :) 

Thank for report!

**Comment by osv** [comment]
Hello, I wrote acceptance tests for this package in web,html,jade,slim modes and found several other bugs.  but for now I hope this issue is fixed and package willbe available in Melpa soon.

**Comment by aiguofer** [comment]
Awesome, it's working great. Thanks!
