### ISSUE TITLE
Enable tern between <script> tags example in README incorrect (maybe?)

### ISSUE THREAD

**Issue by aiguofer** [osv/company-web#9]
The snippet in the README is:

```
;; Enable JavaScript completion between <script>...</script> etc.
(defadvice company-tern (before web-mode-set-up-ac-sources activate)
  "Set `tern-mode' based on current language before running company-tern."
  (if (equal major-mode 'web-mode)
      (let ((web-mode-cur-language
             (web-mode-language-at-pos)))
        (if (or (string= web-mode-cur-language "javascript")
               (string= web-mode-cur-language "jsx")
               )
            (unless tern-mode (tern-mode))
          (if tern-mode (tern-mode))))))
```

I believe the purpose of the last line is to disable `tern-mode` if we're not in a javascript section. If that's the case, the line should read `(if tern-mode (tern-mode -1))))))`.

If that's the case I can make the change if you want me to, or you can go ahead.

Thanks for a great lib!

**Comment by osv** [comment]
Yes, thanks! I get it advice from here https://github.com/fxbois/web-mode/issues/427

Readme updated.
